name: sunday_platform_exemple
description: "A flutter project to showcase sunday_platform components"
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sunday_platform:
    path: ../
  sunday_core: ^0.0.3
  color_theme_provider: ^1.1.1
  macos_ui: ^2.0.9
  fluent_ui: ^4.11.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
