name: sunday_platform
description: "A Flutter package providing universal UI components with custom styles, Cupertino, and Material design options."
version: 0.2.5
homepage: https://github.com/sunday-team/sunday_platform

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  color_theme_provider: ^1.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  macos_ui: ^2.0.9
  sunday_core: ^0.0.3
  sunday_get_storage: ^2.1.1
  universal_io: ^2.2.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0