name: sunday_ui
description: "A Flutter package providing universal UI components with custom styles, Cupertino, and Material design options."
version: 0.1.0
homepage: https://github.com/sunday-team/sunday_ui

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sunday_core: ^0.0.3
  universal_io: ^2.2.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0