name: sunday_ui
description: "A Flutter package providing universal UI components with custom styles, Cupertino, and Material design options."
version: 0.0.2
homepage: https://github.com/sunday-team/sunday_ui

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sunday_core: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0